### PR TITLE
Implement LV2_OPTIONS__options feature

### PR DESCRIPTION
**Pull request by johannes-mueller**
This is now put into the lv2_urid crate. I am unsure if that's the right place. But it can easily be moved to other places.

### CODE REVIEW

**Comment by YruamaLairba** [comment]
Yes, it's not at the right place. The rust-LV2 framework is organized to have one crate per lv2 extension. Look how we implemented other spec : for example, in the folder "time" you have the "lv2-time" crate implementing the "lv2-time" extension.

**Comment by johannes-mueller** [comment]
> Yes, it's not at the right place. The rust-LV2 framework is organized to have one crate per lv2 extension. Look how we implemented other spec : for example, in the folder "time" you have the "lv2-time" crate implementing the "lv2-time" extension.

Ok. I set up a proper lv2-optons crate.

I will adjust the stuff in my #74 accordingly.

Thx

**Comment by Janonard** [comment]
Thank you for your request. However, I'm sorry to say that I must reject this PR since it simply doesn't implement the specifications. A proper implementation would consist of an `Options` struct that abstracts the full functionality of the two `get` and `set` function pointers from an `LV2_Options_Interface` struct in a rusty way.

Please take a look at the [`StoreHandle` struct from the state crate](https://github.com/RustAudio/rust-lv2/blob/613dbdef3b8d9ca5112d461c9d245e0d44436182/state/src/raw.rs#L14), it's API and how it was implemented. The options spec should be implemented in a similar way, since these two features are very similar in nature and maintaining a consistent API style increases the usability of the library.

Please implement the options specification with an API similar to the state crate and create a new pull request.

**Comment by johannes-mueller** [comment]
I implemented the a trait like `LV2_Options_Interface`. However it still needs some work. I will place it as a draft PR. It turns out that especially the `get` function is difficult to test, as no real life host seems to actually implement it. Do you know of one?

**Comment by Janonard** [comment]
I haven't had a look at the options spec yet and I especially haven't had a look at other hosts. We've been implementing "the host" for every test manually, conforming to the standard. Therefore, only little official testing "in the wild" has been done yet.

**Pull request closed without merging**
