### PR TITLE
Cross bindings

### PR DESCRIPTION
**Pull request by YruamaLairba**
It add experimental bindings for arm and aarch64
Also update and improve the systool README

### CODE REVIEW

**Comment by YruamaLairba** [comment]
@Janonard i can add bindings for *-pc-windows-gnu targets but i don't know if it worth. Even if it's not identical to x86_64-pc-windows-msvc, it's fully compatible. The only noticeable difference is the signed/unsigned bindings on enum, which is irrelevant.

**Comment by Janonard** [comment]
I guess you can merge the gnu and msvc bindings. I used to be a little anxious about mixing bindings that aren't 100% identical, but given that the difference between signed and unsigned bindings is never relevant (and would even be annoying when you want to target both targets), I now think it's okay.

Also, does the existence of this PR mean that you're abandoning #64?

**Comment by YruamaLairba** [comment]
> Also, does the existence of this PR mean that you're abandoning #64?

Yes. If i remember correctly, you forked it, did some change, and merged back to develop branch

**Comment by YruamaLairba** [comment]
@Janonard i updated the supported target section of README.md. I tried to separate *binding* concept from *supported target* concept. I'm not sure if my explanation are clear between supported target, usable target, experimental feature gated by `experimental-targets`

**Comment by Janonard** [comment]
I think you mean the right thing, but it isn't that clear yet: A target has three states: It may be missing from the `sys`-crate, it may be included but not supported, or it may be included and supported. The key difference is that for a supported target, there has to be maintainer who can trace problems regarding that target by executing a plugin with a certain host of that target. This has to be stated clearly and precisely.

**Comment by YruamaLairba** [comment]
I fixed explanation about target support requirement. For the rest, i don't know how to make it better. Maybe by presenting tables differently ? One difficulty in explanations is the "experimental-targets" feature, it doesn't really act as a gate for "unsupported but usable" targets. It may more clear if we rename this feature as "experimental-bindings", isn't it ?

**Comment by Janonard** [comment]
#80 is this better? If so, please pull `develop` and add your ARM bindings to Tier 2, so I can merge this PR!

**Comment by YruamaLairba** [comment]
i hope i fixed all my errors. Some of them was not detected by the automatic check

**Review by Janonard — APPROVED** [review]
Looks good!

**Pull request merged**
