### PR TITLE
Pre-generated LV2 API bindings

### PR DESCRIPTION
**Pull request by YruamaLairba**
It works but need a lot of polishing:
## build.rs:
* by default:
  * if the current target triple is in `sys/build_data/valid_targets.txt`, the build.rs script copy sys/build_data/bindings.rs to `$OUT`
  * otherwise, build.rs script fails giving instruction to use bindgen
* user include lv2-sys and enable "bindgen" feature:
*  as before, it build and run bindgen

## maintenance script
The maintenance script source is in `sys/bindgen`. I add it to the workspace, and i created an alias that `cargo run` it. So, when you are in the workspace, `cargo lv2-sys-bindgen` will generate all files found in `sys/build_data`.

## other changes
* remove the layout tests from the generated bindings
* use a white-list too keep only lv2 related stuff bindings

## fix
* fix a conditional compilation issue preventing compilation on `*-windows-gnu` targets

## benefit
* decrease building time
* remove clang requirements
* make cross-compiling easier since clang requirements are removed

EDIT: 15/04/2020

### CODE REVIEW

**Comment by YruamaLairba** [comment]
i think it enough polished for a review, but some remaining details annoying me a bit:
- should i share a bindings function between my script and the build.rs to ensure close as possible results ?
- I may misuse the feature system:
  - use bindgen at build.rs step need direct to depend directly on lv2-sys to activate the feature.
  - should i consider pregenerated bindings as a feature too ?
- test and check: since it use an exclusive conditional compilation, the build.rs need two different compilation to be check; is it an issue ?

**Comment by Janonard** [comment]
The title already says it: This solution is quite hacky! :sweat_smile: Maybe you could try some thing to make it more solid:

First of all, you could include the the pre-generated bindings in the `src` folder and choose either a binding or the generated one using [conditional compilation](https://doc.rust-lang.org/reference/conditional-compilation.html). Rust's conditional compilation features are quite powerful and lets you filter with more meaning instead of just listing all targets into a file. For example, you could use one binding for all Linuxes and another for all Windows targets.

You could also try to bundle the code to generate a binding in one place. Then, the manual generation process and the automated one would just be different ways to execute the same code, improving the reproducibility. The comparison test between the pre-generated and on-the-fly bindings is also missing, you'll still need to add that!

Also, what's the use of `sys/bindgen`?

**Comment by YruamaLairba** [comment]
> First of all, you could include the the pre-generated bindings in the src folder and choose either a binding or the generated one using conditional compilation. Rust's conditional compilation features are quite powerful and lets you filter with more meaning instead of just listing all targets into a file. 

This is what i'd like to do, but there is no way to do conditional compilation with target triple and i didn't want to make an error by guessing the equivalent "target_*" combination.

>You could also try to bundle the code to generate a binding in one place.

Is it fine to embed a crate in another crate and using it as a dependency ?

 > The comparison test between the pre-generated and on-the-fly bindings is also missing, you'll still need to add that!

For simplicity, can i assume equivalence for all u32/i32 (not only those mapping an enum) ? 

> Also, what's the use of sys/bindgen?

Sorry, i should include a small README here. Usage: `cargo run -p lv2-sys-bindgen` or `cargo lv2-sys-bindgen` which is just an alias. There is no parameters. Notice that it doesn't work if you use the binary directly.

**Comment by YruamaLairba** [comment]
I did some change and i will update my first message :
* now, there is a public `generate_bindings` in lv2-sys-bindgen that is used everywhere generating bindings is needed.
* I have written an integration test for lv2-sys crate that check if the pre-generated bindings and  a generated one is equivalent. It just compare lines by lines and ignore all u32/i32 difference.
* I have added a README.md for lv2-sys-bindgen script.
* I fixed sys/lib.rs, it prevented to use the i32/u32 equivalence for enum, and it wasn't working with "*windows-gnu" targets.
* I added the possibility to do "cross-compiled" bindings. As beneficial side effect, it prevent to generate invalid bindings during the `build.rs` script.

**Comment by YruamaLairba** [comment]
f***, my integration test doesn't work, formating and order of element change between the platform

**Comment by YruamaLairba** [comment]
I was so close this time ;-(

@Janonard do you know why bindgen under "ubuntu" produce more symbol than expected ? If you look the test result, my test fails because it finds symbols that are supposed to be filtered out by whitelists when bindings are generated.

**Comment by Janonard** [comment]
I can not execute your binding generation script, because it assumes that the environment variable `CARGO_MANIFEST_DIR` is set, which isn't the case when the executable form of the script is run.

**Comment by Janonard** [comment]
I can not execute your binding generation script, because it assumes that the environment variable `CARGO_MANIFEST_DIR` is set, which isn't the case when the executable form of the script is run. Therefore, I unfortunately can not help you :/

May I ask how you would handle different bindings for different targets? For example, you could solve your "`u32` = `i32`?" problem by discovering which targets use `i32` and which use `u32` and choosing the right binding for them.

Also, the supported targets printed by `rustc` aren't necessarily the targets for which the bindings are correct. For example, you don't have the libc headers of MSVC on your Linux machine and therefore, you simply can not generate correct bindings. On the other hand, if you would use the individual properties from conditional compilation, you would use semantic categories to choose a binding. For example, the bindings generated by one Linux machine should be valid for all Linux targets since Linux is Posix-compatible.

However, I see your struggle and wonder if I should lower my expectations. For example, we could limit the support to those targets with pre-generated bindings and remove the comparison test. We could still "easily" support other targets by generating bindings for them and if we need to check the validity of a binding, we can simply generate and compare it manually. This however would mean that the code generation doesn't have to work both off- and online and will make it way simpler.

Maybe you could try the following approach instead: Rework your `lv2-sys-bindgen` program to only take the path to the LV2 headers and a path to a file. Then, it uses `bindgen` to generate a binding and saves it to the given file. This program then can be used in a Makefile or [cargo make](https://crates.io/crates/cargo-make) to place bindings in the `src` folder of `lv2-sys`. These bindings are then strapped together in `lib.rs` using conditional compilation. If we feel like the bindings are wrong for one platform, we only need to generate a binding and compare it with the one in the crate.

What do you thing about that? I must admit that my expectations were to high, this seems more realistic.

**Comment by YruamaLairba** [comment]
You aren't supposed to run directly the executable form of the script! Use `cargo lv2-sys-bindgen` instead. I have written a README explaining that.

For the i32/u32 difference on enum representation, my current strategy is to ignore it since, in our case, it doesn't alter the layout of the enum. But i can change my script to take care of this difference.

>On the other hand, if you would use the individual properties from conditional compilation, you would use semantic categories to choose a binding.

i don't understand of what you'r talking about here. What is "semantic categories" ?

>For example, the bindings generated by one Linux machine should be valid for all Linux targets since Linux is Posix-compatible.

I don't know well the Posix standard, but i don't think we can do this assumption since there is one linux (exotic) target triple where enum doesn't map to u32 or i32.

> This program then can be used in a Makefile or [cargo make](https://crates.io/crates/cargo-make) to place bindings in the `src` folder of `lv2-sys`. These bindings are then strapped together in `lib.rs` using conditional compilation.

I don't like so much this way for a technical reason. As i already said, it's not possible to use directly target-triple to do conditionnal compilation. You can try to guess the cfg(target_*) equivalent, but it's error prone and may produce horrible condition.

Ps: out off topic, i prefer [xtask](https://github.com/matklad/cargo-xtask) approach for scripting; It has several advantage over cargo-make and makefile since it's only based on cargo and rustc:
- cross-plaform 
- no need to install anything
- don't require to know other languages than rust
The only drawback, is writing the xtask script; you need to write a small CLI application

For my "bindings file equivalence check", i'm really disgusted because technically it works: it show me bindings that aren't supposed to be here, the problem is on the ubuntu bindgen side.

**Comment by YruamaLairba** [comment]
@Janonard i forgot to ask you to run test, on different platform if possible, to see how sensible is my test and what subtle difference i can expect.

**Comment by YruamaLairba** [comment]
I did what you said on lv2-sys-bindgen. I don't find it very useful for "makefile" purpose since bindgen executable can do the same job if you pass the correct flags. I will move bindings comparison logic in it to make more useful.

**Comment by YruamaLairba** [comment]
I did what you said on lv2-sys-bindgen. I don't find it very useful for "makefile" purpose since bindgen executable can do the same job if you pass the correct flags. I will move bindings comparison logic in it to make more useful.
lol, forgot to validate the message

**Comment by Janonard** [comment]
Do you want your changes to arrive in v0.6 or can you wait for v0.7? If this is the case, I could simply finish the documentation for the new sys crate, implement the missing state features (#67) and the release it.

**Comment by YruamaLairba** [comment]
@Janonard 
I short term, i think the current set of usable target (supported and experimental) is too restrictive. If it possible, i think we should also put experimental binding for x86_64 macos, aarch64 linux and arm* linux. We can also mark "TODO, feedback needed" as verification of those targets.  I you want, i can give you my cross-compiled bindings, or tell you what i did to have it.

In long term, If we remove some unecessary and unusable stuff( _bindgen_union_align, va_list) we could make a bindings usable for almost all unix targets. The experimental feature would be kept for untested target.

**Comment by Janonard** [comment]
Agreed, but only if it's clear to the user that we don't **support** these platforms, they're only **usable**.

**Comment by YruamaLairba** [comment]
I close, most of change here have been integrated through a forked branch

**Pull request closed without merging**
