### PR TITLE
Urid restructure (closes #45)

### LINKED ISSUE #45: Separate URID crate
The `URI`, `UriBound` and `URID` systems are very useful, so useful that they could be used by other projects completely separate from the LV2 ecosystem.

Therefore, all URI-related stuff should be bundled in an individual crate; Maybe the `lv2-urid` crate, maybe another one.

### PR DESCRIPTION
**Pull request by Janonard**
This pull request closes #45 by moving the `Uri`, `UriBuf` and `UriBound` to the `lv2_urid` crate and the URID mapping features to the `lv2_core` crate. This implies that `lv2_core` now depends on `lv2_urids` and that `lv2_core` isn't a dependency for some crates.

A downside of the pull request is that it breaks up the specification <-> crate relationship.

This is only a draft since I haven't finished the documentation yet.

### CODE REVIEW

**Comment by YruamaLairba** [comment]
I'm sorry to say something going against your work, but from my point of view, keeping the specification <-> crate relationship is important for clarity. I think it's more important to keep that clarity than making something that maybe someone else will use elsewhere.

**Comment by Janonard** [comment]
Yes, maybe you're right with the relationship. The only thing thatis bothering me is that the `Uri` and `URID` types are split between two crates and that every crate has to dependend on `lv2-core` and `lv2-urid` in order to use `URID`s. You must admit that this is perfect!

Another solution might be to introduce a third, common crate that both `lv2-core` and `lv2-urid` depend on. However, this will add yet another crate to the project and when one of the `lv2-` crates `pub use`s one of the types in the common crate, it appears as if these were part of the `lv2-` crate.

What do you think about that?

**Comment by YruamaLairba** [comment]
In point of view, all crate named lv2-* are meant to be used in lv2 context, so it shouldn't target stuff other than lv2 stuff. So, in practice, at this step of development, the only use of urids is with a plugin, so, in my opinion, the lv2-core dependence for lv2-urids isn't a big issue.

For a longer term view, at some point, i think we may need to have a utility crate to handle RDF stuff.  Then, this may have sense to move Uri related stuff here.

**Comment by Janonard** [comment]
That's more or less what I'm proposing: Moving `Uri` and `URID` to an independent crate (maybe new project all-together?), which may become this RDF crate later on. But I think that we should do it now, since the longer we wait, the more code we have to change.

**Comment by YruamaLairba** [comment]
No, i was more thinking to your alternative solution, having a third new crate where to put Uri (but not urid) stuff. I don't want to mix Uri and urids for some reasons :
* The Uri is a wide concept with general applications on which the lv2 specification is build. All lv2 extensions depends on it and it's not possible to build plugin without it.
* urids instead, is more a specific application and is a concept introduced by a lv2 specification. Many lv2 specifications don't depends on it, and you can build some plugin without it.

So, i'm **ok** to create a separate crate for Uri. It has sens for me since some lv2 extensions build binaries without API dependence to the core specification.
So, i'm **not ok** to change the lv2_urid crate except to update the dependence to Uri (and remove the lv2_core dependence at same time).

**Comment by Janonard** [comment]
I don't think that URI and URID should be separate, because the concept of URI is barely enough to fill a single crate. In our current implementation, a URI is simply a `CStr`. That's it. Even the `UriBound` trait is more useful for the URID system that for anything else.

On the other hand: You don't need any dependencies to `lv2-sys` to create a common URID crate, since the concept is so simple. Please, let me draft a pull request to convince you that a common URID crate is the way to go!

**Pull request closed without merging**
